"""
Pydantic schemas and event envelopes for the ISAAC Industrial Event Streaming Layer.
"""

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


def generate_uuid() -> str:
    """Generate a standard UUIDv4 string."""
    return str(uuid.uuid4())


def get_current_utc_iso() -> str:
    """Generate current UTC ISO-8601 timestamp string."""
    return datetime.now(timezone.utc).isoformat()


class IndustrialEventEnvelope(BaseModel):
    """
    Standardized envelope for industrial machine sensor telemetry events.
    Contains rigorous provenance metadata, correlation trace ID, and physical readings.
    """
    event_id: str = Field(default_factory=generate_uuid, description="Globally unique event UUIDv4")
    trace_id: str = Field(default_factory=generate_uuid, description="Distributed correlation trace ID")
    timestamp_utc: str = Field(default_factory=get_current_utc_iso, description="ISO-8601 UTC event generation timestamp")
    source: str = Field(default="SIMULATOR", description="Originating ingestion source (e.g. SIMULATOR, PHYSICAL_EDGE_IOT)")
    machine_id: str = Field(..., description="Target industrial machine identifier (e.g. M14860)")
    machine_type: str = Field(default="M", description="Machine grade variant: L (Light), M (Medium), H (Heavy)")
    
    # Physical Sensor Readings
    air_temperature_k: float = Field(..., ge=200.0, le=400.0, description="Ambient air temperature in Kelvin")
    process_temperature_k: float = Field(..., ge=200.0, le=400.0, description="Process temperature in Kelvin")
    rotational_speed_rpm: float = Field(..., ge=500.0, le=4000.0, description="Spindle rotational speed in RPM")
    torque_nm: float = Field(..., ge=0.0, le=200.0, description="Shaft torque in Newton-meters")
    tool_wear_min: int = Field(..., ge=0, le=500, description="Cumulative tool wear duration in minutes")
    
    # Optional metadata
    udi: Optional[int] = Field(default=None, description="Universal Unique Device Identifier sequence index")
    scenario: Optional[str] = Field(default=None, description="Simulation scenario label if generated by simulator")
    schema_version: str = Field(default="1.0", description="Event envelope specification schema version")
    extra_attributes: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary extension metadata")

    def to_sensor_dict(self) -> Dict[str, Any]:
        """Extract flat dictionary formatted for prediction service and database models."""
        return {
            "machine_id": self.machine_id,
            "machine_type": self.machine_type.upper(),
            "air_temperature_k": self.air_temperature_k,
            "process_temperature_k": self.process_temperature_k,
            "rotational_speed_rpm": self.rotational_speed_rpm,
            "torque_nm": self.torque_nm,
            "tool_wear_min": self.tool_wear_min,
            "udi": self.udi,
            "source": self.source,
            "event_id": self.event_id,
            "trace_id": self.trace_id,
            "timestamp": self.timestamp_utc,
            "scenario": self.scenario,
        }


class KafkaEventMetadata(BaseModel):
    """Kafka broker-specific transmission and delivery metadata."""
    topic: str
    partition: Optional[int] = None
    offset: Optional[int] = None
    published_at: Optional[str] = None
    consumed_at: Optional[str] = None
    delivery_latency_ms: Optional[float] = None


class StreamStatusResponse(BaseModel):
    """Comprehensive status payload for event-streaming health and metrics."""
    streaming_active: bool
    mode: str = Field(description="'KAFKA' | 'LOCAL_FALLBACK' | 'DISABLED'")
    kafka_enabled: bool
    kafka_connected: bool
    bootstrap_servers: str
    telemetry_topic: str
    predictions_topic: str
    consumer_group: str
    messages_published: int
    messages_consumed: int
    messages_failed: int
    fallback_messages_routed: int
    latest_event_id: Optional[str] = None
    latest_event_timestamp: Optional[str] = None
    details: Optional[str] = None
